### ISSUE TITLE
"Add" doesn't work if PrimaryKey column is not Auto Incremental

### ISSUE THREAD

**Issue by HamedMoghadasi** [nimayazdi93/NiORM#2]
`includePrimaryKey` is hard coded by `false` value, It means that even If we pass a value for the primary key, this method will not consider it! 
so if the primary Key column of a table was not auto incremental, the user will face an error that `PrimaryKey cannot be null!`.

![image](https://user-images.githubusercontent.com/33372599/213304267-0a2cefc7-70df-4127-8ce6-9808b15cf4a2.png)

**Comment by nimayazdi93** [comment]
Dear Hamed, 
Very thanks for your review, i will fix it ASAP. 🌹

**Comment by nimayazdi93** [comment]
Dear Hamed,
I refactored it with a new parameter inside PrimaryKey!
